engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        javascript:
          mass_threshold: 80
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- "config/"
- "app/assets/javascripts/application.js"
- "spec/"
